// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: observer.proto

package observerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateObserverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObserverRequest) Reset() {
	*x = UpdateObserverRequest{}
	mi := &file_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObserverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObserverRequest) ProtoMessage() {}

func (x *UpdateObserverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObserverRequest.ProtoReflect.Descriptor instead.
func (*UpdateObserverRequest) Descriptor() ([]byte, []int) {
	return file_observer_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateObserverRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateObserverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObserverResponse) Reset() {
	*x = UpdateObserverResponse{}
	mi := &file_observer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObserverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObserverResponse) ProtoMessage() {}

func (x *UpdateObserverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObserverResponse.ProtoReflect.Descriptor instead.
func (*UpdateObserverResponse) Descriptor() ([]byte, []int) {
	return file_observer_proto_rawDescGZIP(), []int{1}
}

var File_observer_proto protoreflect.FileDescriptor

const file_observer_proto_rawDesc = "" +
	"\n" +
	"\x0eobserver.proto\x12\n" +
	"observerpb\"1\n" +
	"\x15UpdateObserverRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x16UpdateObserverResponse2e\n" +
	"\bObserver\x12Y\n" +
	"\x0eUpdateObserver\x12!.observerpb.UpdateObserverRequest\x1a\".observerpb.UpdateObserverResponse\"\x00B]\n" +
	"\x17com.senzing.observer.pbB\rObserverProtoP\x01Z1github.com/senzing-garage/go-observing/observerpbb\x06proto3"

var (
	file_observer_proto_rawDescOnce sync.Once
	file_observer_proto_rawDescData []byte
)

func file_observer_proto_rawDescGZIP() []byte {
	file_observer_proto_rawDescOnce.Do(func() {
		file_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observer_proto_rawDesc), len(file_observer_proto_rawDesc)))
	})
	return file_observer_proto_rawDescData
}

var file_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_observer_proto_goTypes = []any{
	(*UpdateObserverRequest)(nil),  // 0: observerpb.UpdateObserverRequest
	(*UpdateObserverResponse)(nil), // 1: observerpb.UpdateObserverResponse
}
var file_observer_proto_depIdxs = []int32{
	0, // 0: observerpb.Observer.UpdateObserver:input_type -> observerpb.UpdateObserverRequest
	1, // 1: observerpb.Observer.UpdateObserver:output_type -> observerpb.UpdateObserverResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_observer_proto_init() }
func file_observer_proto_init() {
	if File_observer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observer_proto_rawDesc), len(file_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observer_proto_goTypes,
		DependencyIndexes: file_observer_proto_depIdxs,
		MessageInfos:      file_observer_proto_msgTypes,
	}.Build()
	File_observer_proto = out.File
	file_observer_proto_goTypes = nil
	file_observer_proto_depIdxs = nil
}
